{% set name = "crystal-toolkit" %}
{% set version = "2023.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/crystal_toolkit-{{ version }}.tar.gz
  sha256: d17c15c3b6ab6d800da012db332b64abea1f826581eee47a89aedfebc723aa2c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=45
    - setuptools-scm >=6.2,<8
    - jupyter_packaging
    - pip
  run:
    - python >=3.9
    - crystaltoolkit-extension
    - dash-mp-components >=0.4.38
    - dash >=2.11.0
    - flask-caching
    - frozendict
    - pymatgen
    - scikit-image
    - scikit-learn
    - shapely
    - webcolors
    - pydantic-settings
    - mp-api
    - jupyterlab >=3

test:
  imports:
    - crystal_toolkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/crystaltoolkit
  summary: Crystal Toolkit is a web app framework from the Materials Project
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyterlab-extension/LICENSE

extra:
  recipe-maintainers:
    - awvwgk
